const fs = require('node:fs');
const path = require('node:path');
const { AttachmentBuilder } = require('discord.js');
const { ensureDir, fillTemplate } = require('./utils');

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

async function fetchAllMessages(channel) {
  const messages = [];
  let before;
  while (true) {
    const batch = await channel.messages.fetch({ limit: 100, before });
    if (!batch.size) break;
    messages.push(...batch.values());
    before = batch.last().id;
    if (batch.size < 100) break;
  }
  return messages.reverse();
}

async function createTranscript(channel, ticket, config) {
  const options = config.transcript?.html || {};
  const messages = (await fetchAllMessages(channel)).filter((message) => {
    return options.includeBotMessages || !message.author.bot;
  });
  const title = fillTemplate(options.title || '{guild} Ticket Transcript', {
    guild: channel.guild.name,
    ticketName: channel.name
  });
  const rows = messages.map((message) => {
    const attachments = options.includeAttachments
      ? [...message.attachments.values()].map((file) => `<a href="${escapeHtml(file.url)}">${escapeHtml(file.name || file.url)}</a>`).join('<br>')
      : '';
    const content = escapeHtml(message.content || '').replace(/\n/g, '<br>');
    return `<article class="message">
      <img src="${escapeHtml(message.author.displayAvatarURL())}" alt="">
      <div>
        <header><strong>${escapeHtml(message.author.tag)}</strong><time>${escapeHtml(message.createdAt.toLocaleString())}</time></header>
        <p>${content || '<em>No text content</em>'}</p>
        ${attachments ? `<div class="attachments">${attachments}</div>` : ''}
      </div>
    </article>`;
  }).join('\n');
  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { --accent: ${escapeHtml(options.accentColor || config.colors?.primary || '#5865F2')}; --bg: #101114; --panel: #181A20; --text: #F4F5F7; --muted: #AEB4C0; }
    * { box-sizing: border-box; }
    body { margin: 0; font-family: Inter, Segoe UI, Arial, sans-serif; background: var(--bg); color: var(--text); }
    .top { padding: 28px; background: linear-gradient(135deg, var(--accent), #111827); border-bottom: 1px solid #2A2D35; }
    .top h1 { margin: 0 0 8px; font-size: 28px; letter-spacing: 0; }
    .top p { margin: 0; color: #E7E9EF; }
    main { width: min(980px, calc(100% - 28px)); margin: 22px auto; }
    .meta { display: grid; gap: 10px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); margin-bottom: 18px; }
    .meta div, .message { background: var(--panel); border: 1px solid #2A2D35; border-radius: 8px; }
    .meta div { padding: 12px 14px; color: var(--muted); }
    .meta strong { display: block; color: var(--text); margin-bottom: 3px; }
    .message { display: grid; grid-template-columns: 42px 1fr; gap: 12px; padding: 14px; margin-bottom: 10px; }
    .message img { width: 42px; height: 42px; border-radius: 50%; }
    header { display: flex; gap: 10px; align-items: baseline; flex-wrap: wrap; }
    time { color: var(--muted); font-size: 12px; }
    p { margin: 7px 0 0; line-height: 1.5; word-break: break-word; }
    a { color: #9BB2FF; }
    footer { color: var(--muted); text-align: center; padding: 22px; }
  </style>
</head>
<body>
  <section class="top"><h1>${escapeHtml(options.brandName || 'Support Team')}</h1><p>${escapeHtml(title)}</p></section>
  <main>
    <section class="meta">
      <div><strong>Ticket</strong>${escapeHtml(channel.name)}</div>
      <div><strong>Owner</strong>${escapeHtml(ticket.username || ticket.ownerId)}</div>
      <div><strong>Category</strong>${escapeHtml(ticket.categoryId)}</div>
      <div><strong>Created</strong>${escapeHtml(new Date(ticket.createdAt).toLocaleString())}</div>
    </section>
    ${rows || '<p>No messages found.</p>'}
  </main>
  <footer>${escapeHtml(options.footerText || 'Generated by Dragonia Ticket Bot')}</footer>
</body>
</html>`;
  const dir = path.resolve(__dirname, '..', config.storage?.transcriptsDir || 'transcripts');
  ensureDir(dir);
  const fileName = `${channel.name}-${Date.now()}.html`;
  const filePath = path.join(dir, fileName);
  if (config.transcript?.saveToFile !== false) fs.writeFileSync(filePath, html, 'utf8');
  return {
    attachment: new AttachmentBuilder(Buffer.from(html, 'utf8'), { name: fileName }),
    filePath,
    html
  };
}

module.exports = {
  createTranscript
};
